# Generated by Django 3.2.3 on 2021-05-24 19:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0002_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewgame',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='body',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
