# Generated by Django 3.2.3 on 2021-05-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210526_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOkay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=260)),
            ],
        ),
    ]
