# Generated by Django 3.2.3 on 2021-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_modelokay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOkay2',
            fields=[
                ('price', models.CharField(max_length=260)),
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelOkay',
        ),
    ]
