# Generated by Django 3.2.3 on 2021-05-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelconsoleGames',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WarpGames',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
